<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AimsAdmin', 'doctrine');

/**
 * BaseAimsAdmin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $aim_id
 * @property integer $user_id
 * @property Aims $Aims
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer     getId()          Returns the current record's "id" value
 * @method integer     getAimId()       Returns the current record's "aim_id" value
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method Aims        getAims()        Returns the current record's "Aims" value
 * @method sfGuardUser getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method AimsAdmin   setId()          Sets the current record's "id" value
 * @method AimsAdmin   setAimId()       Sets the current record's "aim_id" value
 * @method AimsAdmin   setUserId()      Sets the current record's "user_id" value
 * @method AimsAdmin   setAims()        Sets the current record's "Aims" value
 * @method AimsAdmin   setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    base_de_datos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAimsAdmin extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('aims_admin');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('aim_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Aims', array(
             'local' => 'aim_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}