<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClubesReunion', 'doctrine');

/**
 * BaseClubesReunion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $club_id
 * @property string $dia
 * @property time $hora
 * @property CfgDias $CfgDias
 * @property Clubes $Clubes
 * 
 * @method integer       getId()      Returns the current record's "id" value
 * @method integer       getClubId()  Returns the current record's "club_id" value
 * @method string        getDia()     Returns the current record's "dia" value
 * @method time          getHora()    Returns the current record's "hora" value
 * @method CfgDias       getCfgDias() Returns the current record's "CfgDias" value
 * @method Clubes        getClubes()  Returns the current record's "Clubes" value
 * @method ClubesReunion setId()      Sets the current record's "id" value
 * @method ClubesReunion setClubId()  Sets the current record's "club_id" value
 * @method ClubesReunion setDia()     Sets the current record's "dia" value
 * @method ClubesReunion setHora()    Sets the current record's "hora" value
 * @method ClubesReunion setCfgDias() Sets the current record's "CfgDias" value
 * @method ClubesReunion setClubes()  Sets the current record's "Clubes" value
 * 
 * @package    base_de_datos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClubesReunion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('clubes_reunion');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('club_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('dia', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('hora', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CfgDias', array(
             'local' => 'dia',
             'foreign' => 'dia'));

        $this->hasOne('Clubes', array(
             'local' => 'club_id',
             'foreign' => 'id'));
    }
}