<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CfgDias', 'doctrine');

/**
 * BaseCfgDias
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $dia
 * @property Doctrine_Collection $ClubesReunion
 * 
 * @method string              getDia()           Returns the current record's "dia" value
 * @method Doctrine_Collection getClubesReunion() Returns the current record's "ClubesReunion" collection
 * @method CfgDias             setDia()           Sets the current record's "dia" value
 * @method CfgDias             setClubesReunion() Sets the current record's "ClubesReunion" collection
 * 
 * @package    base_de_datos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCfgDias extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cfg_dias');
        $this->hasColumn('dia', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ClubesReunion', array(
             'local' => 'dia',
             'foreign' => 'dia'));
    }
}