<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CfgPaises', 'doctrine');

/**
 * BaseCfgPaises
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $pais
 * @property Doctrine_Collection $CfgProvincias
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getPais()          Returns the current record's "pais" value
 * @method Doctrine_Collection getCfgProvincias() Returns the current record's "CfgProvincias" collection
 * @method CfgPaises           setId()            Sets the current record's "id" value
 * @method CfgPaises           setPais()          Sets the current record's "pais" value
 * @method CfgPaises           setCfgProvincias() Sets the current record's "CfgProvincias" collection
 * 
 * @package    base_de_datos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCfgPaises extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cfg_paises');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('pais', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CfgProvincias', array(
             'local' => 'id',
             'foreign' => 'pais_id'));
    }
}