<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CfgTipoDni', 'doctrine');

/**
 * BaseCfgTipoDni
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $tipo
 * @property Doctrine_Collection $tipodni
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method string              getTipo()    Returns the current record's "tipo" value
 * @method Doctrine_Collection getTipodni() Returns the current record's "tipodni" collection
 * @method CfgTipoDni          setId()      Sets the current record's "id" value
 * @method CfgTipoDni          setTipo()    Sets the current record's "tipo" value
 * @method CfgTipoDni          setTipodni() Sets the current record's "tipodni" collection
 * 
 * @package    Sistema de Gestion - Rotaract Rotary e Interact
 * @subpackage model
 * @author     Gaspar Zaragoza
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCfgTipoDni extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cfg_tipo_dni');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('tipo', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUserProfile as tipodni', array(
             'local' => 'id',
             'foreign' => 'tipo_dni'));
    }
}