<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CfgProvincias', 'doctrine');

/**
 * BaseCfgProvincias
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $pais_id
 * @property string $provincia
 * @property CfgPaises $CfgPaises
 * @property Doctrine_Collection $CfgCiudades
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method integer             getPaisId()      Returns the current record's "pais_id" value
 * @method string              getProvincia()   Returns the current record's "provincia" value
 * @method CfgPaises           getCfgPaises()   Returns the current record's "CfgPaises" value
 * @method Doctrine_Collection getCfgCiudades() Returns the current record's "CfgCiudades" collection
 * @method CfgProvincias       setId()          Sets the current record's "id" value
 * @method CfgProvincias       setPaisId()      Sets the current record's "pais_id" value
 * @method CfgProvincias       setProvincia()   Sets the current record's "provincia" value
 * @method CfgProvincias       setCfgPaises()   Sets the current record's "CfgPaises" value
 * @method CfgProvincias       setCfgCiudades() Sets the current record's "CfgCiudades" collection
 * 
 * @package    base_de_datos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCfgProvincias extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cfg_provincias');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('pais_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('provincia', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CfgPaises', array(
             'local' => 'pais_id',
             'foreign' => 'id'));

        $this->hasMany('CfgCiudades', array(
             'local' => 'id',
             'foreign' => 'provincia_id'));
    }
}