<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CfgOcupacion', 'doctrine');

/**
 * BaseCfgOcupacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $ocupacion
 * @property Doctrine_Collection $tipodni
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getOcupacion() Returns the current record's "ocupacion" value
 * @method Doctrine_Collection getTipodni()   Returns the current record's "tipodni" collection
 * @method CfgOcupacion        setId()        Sets the current record's "id" value
 * @method CfgOcupacion        setOcupacion() Sets the current record's "ocupacion" value
 * @method CfgOcupacion        setTipodni()   Sets the current record's "tipodni" collection
 * 
 * @package    Sistema de Gestion - Rotaract Rotary e Interact
 * @subpackage model
 * @author     Gaspar Zaragoza
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCfgOcupacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cfg_ocupacion');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('ocupacion', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUserProfile as tipodni', array(
             'local' => 'id',
             'foreign' => 'ocupacion'));
    }
}