<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CfgProgramas', 'doctrine');

/**
 * BaseCfgProgramas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $programa
 * @property string $logo
 * @property Doctrine_Collection $Clubes
 * 
 * @method string              getPrograma() Returns the current record's "programa" value
 * @method string              getLogo()     Returns the current record's "logo" value
 * @method Doctrine_Collection getClubes()   Returns the current record's "Clubes" collection
 * @method CfgProgramas        setPrograma() Sets the current record's "programa" value
 * @method CfgProgramas        setLogo()     Sets the current record's "logo" value
 * @method CfgProgramas        setClubes()   Sets the current record's "Clubes" collection
 * 
 * @package    base_de_datos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCfgProgramas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cfg_programas');
        $this->hasColumn('programa', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('logo', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Clubes', array(
             'local' => 'programa',
             'foreign' => 'programa'));
    }
}