<?php

/**
 * BasesfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $apodo
 * @property date $fecha_nacimiento
 * @property integer $tipo_dni
 * @property string $nro_dni
 * @property integer $ocupacion
 * @property sfGuardUser $User
 * @property CfgTipoDni $tipodni
 * @property CfgOcupacion $ocupacion
 * 
 * @method integer            getId()               Returns the current record's "id" value
 * @method integer            getUserId()           Returns the current record's "user_id" value
 * @method string             getApodo()            Returns the current record's "apodo" value
 * @method date               getFechaNacimiento()  Returns the current record's "fecha_nacimiento" value
 * @method integer            getTipoDni()          Returns the current record's "tipo_dni" value
 * @method string             getNroDni()           Returns the current record's "nro_dni" value
 * @method CfgOcupacion       getOcupacion()        Returns the current record's "ocupacion" value
 * @method sfGuardUser        getUser()             Returns the current record's "User" value
 * @method CfgTipoDni         getTipodni()          Returns the current record's "tipodni" value
 * @method sfGuardUserProfile setId()               Sets the current record's "id" value
 * @method sfGuardUserProfile setUserId()           Sets the current record's "user_id" value
 * @method sfGuardUserProfile setApodo()            Sets the current record's "apodo" value
 * @method sfGuardUserProfile setFechaNacimiento()  Sets the current record's "fecha_nacimiento" value
 * @method sfGuardUserProfile setTipoDni()          Sets the current record's "tipo_dni" value
 * @method sfGuardUserProfile setNroDni()           Sets the current record's "nro_dni" value
 * @method sfGuardUserProfile setOcupacion()        Sets the current record's "ocupacion" value
 * @method sfGuardUserProfile setUser()             Sets the current record's "User" value
 * @method sfGuardUserProfile setTipodni()          Sets the current record's "tipodni" value
 * 
 * @package    Sistema de Gestion - Rotaract Rotary e Interact
 * @subpackage model
 * @author     Gaspar Zaragoza
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_profile');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('apodo', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('fecha_nacimiento', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('tipo_dni', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('nro_dni', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('ocupacion', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('CfgTipoDni as tipodni', array(
             'local' => 'tipo_dni',
             'foreign' => 'id'));

        $this->hasOne('CfgOcupacion as ocupacion', array(
             'local' => 'ocupacion',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}