<?php

/**
 * AimsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AimsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AimsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Aims');
    }
}