<?php

/**
 * AimsAdminTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AimsAdminTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AimsAdminTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AimsAdmin');
    }
}