<?php

/**
 * CfgCiudadesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CfgCiudadesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CfgCiudadesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CfgCiudades');
    }
}