<?php

/**
 * CfgOcupacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CfgOcupacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CfgOcupacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CfgOcupacion');
    }
}