<?php

/**
 * CfgPaisesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CfgPaisesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CfgPaisesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CfgPaises');
    }
}