<?php

/**
 * CfgProgramasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CfgProgramasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CfgProgramasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CfgProgramas');
    }
}