<?php

/**
 * CfgTipoDniTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CfgTipoDniTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CfgTipoDniTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CfgTipoDni');
    }
}