<?php

/**
 * ClubesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClubesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClubesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Clubes');
    }
}