<?php

/**
 * ClubesReunionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClubesReunionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClubesReunionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClubesReunion');
    }
}