<?php

/**
 * ClubesAdminTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClubesAdminTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClubesAdminTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClubesAdmin');
    }
}