<?php

/**
 * DistritosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DistritosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DistritosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Distritos');
    }
}