<?php

/**
 * Distritos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    base_de_datos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Distritos extends BaseDistritos
{
    public function __toString()
    {
        return sprintf('%s', $this->getDistrito());
    }

    public function getClubesDistritoQuery()
    {
    $q = Doctrine_Query::create()
        ->from('Clubes c')
        ->where('c.distrito_id = ?', $this->getId())
        ->addOrderBy('c.club ASC');
    return $q;
    }
}