<?php

/**
 * Zones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Sistema de Gestion - Rotaract Rotary e Interact
 * @subpackage model
 * @author     Gaspar Zaragoza
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Zones extends BaseZones
{

}