<?php

/**
 * ZonesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ZonesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ZonesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Zones');
    }
}