generator:
  class: sfDoctrineGenerator
  param:
    model_class:           CfgProvincias
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          cfg_provincias
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        fields:
            cfg_paises: {label: "Pais"}
        title:      Administracion de Paises
        display:    [provincia, cfg_paises]
        sort:       pais_id, provincia
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
