sfGuardUserProfile:
  columns:
    id:
      type: integer(8)
      primary: true
      autoincrement: true
    user_id:
      type: integer(8)
    apodo:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fecha_nacimiento:
      type: date
      notnull: false
  relations:
    User:
      class: sfGuardUser
      local: user_id
      foreign: id
      type: one
      foreignType: one
      foreignAlias: Profile
      onDelete: CASCADE
      
Aims:
  connection: doctrine
  tableName: aims
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    aim:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    sigla:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    presidente_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    AimsAdmin:
      local: id
      foreign: aim_id
      type: many
    Distritos:
      local: id
      foreign: aim_id
      type: many
    sfGuardUser:
      local: presidente_id
      foreign: id
      type: one

AimsAdmin:
  connection: doctrine
  tableName: aims_admin
  columns:
    id:
      type: integer(8)
      autoincrement: true
      primary: true
    aim_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    user_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Aims:
      local: aim_id
      foreign: id
      type: one
    sfGuardUser:
      local: user_id
      foreign: id
      type: one

CfgCiudades:
  connection: doctrine
  tableName: cfg_ciudades
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    provincia_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    ciudad:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    CfgProvincias:
      local: provincia_id
      foreign: id
      type: one
    Clubes:
      local: id
      foreign: ciudad_id
      type: many
CfgDias:
  connection: doctrine
  tableName: cfg_dias
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    dia:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      autoincrement: false
  relations:
    ClubesReunion:
      local: id
      foreign: dia_id
      type: many
CfgPaises:
  connection: doctrine
  tableName: cfg_paises
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    pais:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    CfgProvincias:
      local: id
      foreign: pais_id
      type: many
CfgProgramas:
  connection: doctrine
  tableName: cfg_programas
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    programa:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      autoincrement: false
    logo:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Clubes:
      local: id
      foreign: programa_id
      type: many
CfgProvincias:
  connection: doctrine
  tableName: cfg_provincias
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    pais_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    provincia:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    CfgPaises:
      local: pais_id
      foreign: id
      type: one
    CfgCiudades:
      local: id
      foreign: provincia_id
      type: many
Clubes:
  connection: doctrine
  tableName: clubes
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    club:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    email:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    url:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    direccion:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    presidente_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    ciudad_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    distrito_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    programa_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Distritos:
      local: distrito_id
      foreign: id
      type: one
    CfgCiudades:
      local: ciudad_id
      foreign: id
      type: one
    CfgProgramas:
      local: programa_id
      foreign: id
      type: one
    ClubesAdmin:
      local: id
      foreign: club_id
      type: many
    ClubesReunion:
      local: id
      foreign: club_id
      type: many
    sfGuardUser:
      local: presidente_id
      foreign: id
      type: one

ClubesAdmin:
  connection: doctrine
  tableName: clubes_admin
  columns:
    id:
      type: integer(8)
      autoincrement: true
      primary: true
    club_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    user_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Clubes:
      local: club_id
      foreign: id
      type: one
    sfGuardUser:
      local: user_id
      foreign: id
      type: one

ClubesReunion:
  connection: doctrine
  tableName: clubes_reunion
  columns:
    id:
      type: integer(8)
      autoincrement: true
      primary: true
    club_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    dia_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    hora:
      type: time(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    CfgDias:
      local: dia_id
      foreign: id
      type: one
    Clubes:
      local: club_id
      foreign: id
      type: one
Distritos:
  connection: doctrine
  tableName: distritos
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    distrito:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    gd_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    rdr_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    rdi_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    aim_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Aims:
      local: aim_id
      foreign: id
      type: one
    Clubes:
      local: id
      foreign: distrito_id
      type: many
    DistritosAdmin:
      local: id
      foreign: distrito_id
      type: many
    Gobernador:
      class: sfGuardUser
      local: gd_id
      foreign: id
      type: one
    RepresentanteR:
      class: sfGuardUser
      local: rdr_id
      foreign: id
      type: one
    RepresentanteI:
      class: sfGuardUser
      local: rdi_id
      foreign: id
      type: one
 
DistritosAdmin:
  connection: doctrine
  tableName: distritos_admin
  columns:
    id:
      type: integer(8)
      autoincrement: true
      primary: true
    distrito_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    user_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Distritos:
      local: distrito_id
      foreign: id
      type: one
    sfGuardUser:
      local: user_id
      foreign: id
      type: one

